export const productos = [
  {
    title: "Ibanez-KIKOSP3",
    price: 5000,
    category: "electric",
    description: "Kiko Loureiro Signature",
    stock: 200,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_KIKOSP3_TEB_5N_01.png",
  },
  {
    title: "Ibanez-AT100CL",
    price: 7500,
    category: "electric",
    description: "Andy Timmons Signature",
    stock: 300,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_AT100CL_SB_00_07.png",
  },
  {
    title: "Ibanez-JEM77PQ",
    price: 7000,
    category: "electric",
    description: "Steve Vai Signature",
    stock: 400,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_JEM77P_BFP_1P_04.png",
  },
  {
    title: "Ibanez-JEMJRSP",
    price: 1600,
    category: "electric",
    description: "Steve Vai Signature",
    stock: 500,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_JEMJRSP_PK_1P_03.png",
  },
  {
    title: "Ibanez-JS24807",
    price: 1800,
    category: "electric",
    description: "Joe Satriani Signature",
    stock: 400,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_JS2480_MCR_00_02.png",
  },
  {
    title: "Ibanez-PGMM311",
    price: 2700,
    category: "electric",
    description: "Paul Gilbert Signature",
    stock: 300,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_PGMM31_WH_5A_02.png",
  },
  {
    title: "Ibanez-FRM300H",
    price: 1300,
    category: "electric",
    description: "Paul Gilbert Firebird",
    stock: 400,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_FRM300_PR_4L_01.png",
  },
  {
    title: "Ibanez-AW5400B",
    price: 8500,
    category: "acoustic",
    description: "Acoustic Guitar",
    stock: 400,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_AW54_OPN_1P_02.png",
  },
  {
    title: "Ibanez-AE3255X",
    price: 4000,
    category: "acoustic",
    description: "Acoustic Guitar",
    stock: 700,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_AE325_LGS_1X_03.png",
  },
  {
    title: "Ibanez-AE240JR",
    price: 6500,
    category: "acoustic",
    description: "Acoustic Guitar",
    stock: 500,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_AE240JR_MHS_1X_01.png",
  },
  {
    title: "Ibanez-AEWC11C",
    price: 3000,
    category: "acoustic",
    description: "Acoustic Guitar",
    stock: 100,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_AEWC11_TCB_5B_02.png",
  },
  {
    title: "Ibanez-FRH10NX",
    price: 9000,
    category: "electric",
    description: "Acoustic Guitar",
    stock: 500,
    img: "https://www.ibanez.com/common/product_artist_file/file/p_region_PS3CM_33_01.png",
  },
];
